name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'app/**'
      - 'requirements.txt'
      - '.github/workflows/windows-build.yml'

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          py -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE
        shell: pwsh
        run: |
          pyinstaller --onefile -n crawler.exe -p app app\\server.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: crawler-windows
          path: dist/crawler.exe

      - name: Create Release and Upload EXE
        uses: softprops/action-gh-release@v2
        with:
          name: Windows EXE Build
          tag_name: v${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            dist/crawler.exe

